services:
   redis:
     image: redis:7-alpine
     container_name: creatorlens-redis

     ports:
       - "6379:6379"
     restart: unless-stopped

     volumes:
       - redis-data:/data
     
     command: ["redis-server", "--appendonly", "yes"]
   
   rabbitmq:
     image: rabbitmq:4-management
     container_name: creatorlens-rabbitmq

     ports:
       - "5672:5672"
       - "15672:15672"
     restart: unless-stopped

     volumes:
       - rabbitmq-data:/var/lib/rabbitmq
volumes:
  redis-data:
  rabbitmq-data: 
